<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net48;net6.0;net8.0;net10.0</TargetFrameworks>
	<Summary>Easiest way you'll ever write settings for your app. Cross-platform, modular and still a one-liner.
Encrypt, Encode and have full control over hardcoded / dynamic settings.</Summary>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Description>Easiest way you'll ever write settings for your app. This library is built to be modular and one-liner exploiting the powerful serialization capabilities of Json.NET out of the box without any mapping necessary to serialize nested custom objects, dictionaries and lists.</Description>
    <RootNamespace>Nucs.JsonSettings</RootNamespace>
    <PackageId>Nucs.JsonSettings</PackageId>
    <Title>Nucs.JsonSettings</Title>
    <LangVersion>9</LangVersion>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Autosave\**" />
    <EmbeddedResource Remove="Autosave\**" />
    <None Remove="Autosave\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>


</Project>
